export default {
  config: 'Root Settings',
  interface: 'Interface (UI)',
  model_specs: 'Model Specs',
  registration: 'Registration',
  file_config: 'File Config',
  transactions: 'Transactions',
  balance: 'Balance',
  agents: 'Agents',
  agents_config: 'Agents Settings (Global)',
  mcp_servers: 'MCP Servers',
  mcp_settings: 'MCP Settings',
  ocr: 'OCR',
  memory: 'Memory',
  custom_endpoint: 'Custom Endpoint',
  custom_params: 'Customize Endpoint Parameters',
  azure_openai: 'Azure OpenAI',
  aws_bedrock: 'AWS Bedrock',
  anthropic_vertex: 'Anthropic Vertex AI',
  model_config: 'Azure Model Config',
  actions: 'Actions (OpenAPI Specs)',
  turnstile: 'Cloudflare Turnstile',
  assistants_endpoint: 'Assistants API',
  default_params: 'API Default Parameters',
}
