export default {
  config: 'Root Settings',
  file_config: 'File Config',
  interface: 'Interface (UI)',
  model_specs: 'Model Specs',
  registration: 'Registration',
  balance: 'Balance',
  agents: 'Agents',
  mcp_servers: 'MCP Servers',
  aws_bedrock: 'AWS Bedrock',
  assistants_endpoint: 'Assistants API',
  custom_endpoint: 'Custom Endpoint',
  azure_openai: 'Azure OpenAI',
  model_config: 'Azure Model Config',
  default_params: 'API Default Parameters',
}
