import type { ReactElement } from 'react'
import {
  Rocket,
  Sparkles,
  Monitor,
  Cloud,
  Settings,
  BookOpen,
  Globe,
  Hammer,
  FileText,
  Lock,
  KeyRound,
  Shield,
  HardDrive,
  FileCode,
  Plug,
  Braces,
  Bot,
  Wrench,
  Database,
  // Docker, npm, Helm, hosting
  Container,
  Package,
  Ship,
  Server,
  Network,
  TrainFront,
  // Auth
  Mail,
  Users,
  // OAuth providers
  Apple,
  MessageCircle,
  Github,
  Chrome,
  // Features
  Puzzle,
  Palette,
  Image,
  Upload,
  Link,
  MessageSquare,
  Search,
  Brain,
  ScanText,
  GitFork,
  Import,
  Share2,
  Clock,
  Zap,
  // Config & structure
  Variable,
  Code,
  Blocks,
  Layers,
  LayoutDashboard,
  // Tools
  CloudSun,
  Sigma,
  Paintbrush,
  Mic,
  Coins,
  // Dev & guides
  BarChart3,
  Activity,
  Languages,
  TestTube,
  Bug,
  SquareTerminal,
  ScrollText,
  Fingerprint,
  // Differentiated sidebar icons
  ListFilter,
  Bookmark,
  Waypoints,
  Warehouse,
  Flame,
  Wand2,
  PenTool,
  Radar,
  ShieldCheck,
  UserCheck,
  Building2,
} from 'lucide-react'

const icons: Record<string, ReactElement> = {
  Rocket: <Rocket />,
  Sparkles: <Sparkles />,
  Monitor: <Monitor />,
  Cloud: <Cloud />,
  Settings: <Settings />,
  BookOpen: <BookOpen />,
  Globe: <Globe />,
  Hammer: <Hammer />,
  FileText: <FileText />,
  Lock: <Lock />,
  KeyRound: <KeyRound />,
  Shield: <Shield />,
  HardDrive: <HardDrive />,
  FileCode: <FileCode />,
  Plug: <Plug />,
  Braces: <Braces />,
  Bot: <Bot />,
  Wrench: <Wrench />,
  Database: <Database />,
  Container: <Container />,
  Package: <Package />,
  Ship: <Ship />,
  Server: <Server />,
  Network: <Network />,
  TrainFront: <TrainFront />,
  Mail: <Mail />,
  Users: <Users />,
  Apple: <Apple />,
  MessageCircle: <MessageCircle />,
  Github: <Github />,
  Chrome: <Chrome />,
  Puzzle: <Puzzle />,
  Palette: <Palette />,
  Image: <Image />,
  Upload: <Upload />,
  Link: <Link />,
  MessageSquare: <MessageSquare />,
  Search: <Search />,
  Brain: <Brain />,
  ScanText: <ScanText />,
  GitFork: <GitFork />,
  Import: <Import />,
  Share2: <Share2 />,
  Clock: <Clock />,
  Zap: <Zap />,
  Variable: <Variable />,
  Code: <Code />,
  Blocks: <Blocks />,
  Layers: <Layers />,
  LayoutDashboard: <LayoutDashboard />,
  CloudSun: <CloudSun />,
  Sigma: <Sigma />,
  Paintbrush: <Paintbrush />,
  Mic: <Mic />,
  Coins: <Coins />,
  BarChart3: <BarChart3 />,
  Activity: <Activity />,
  Languages: <Languages />,
  TestTube: <TestTube />,
  Bug: <Bug />,
  SquareTerminal: <SquareTerminal />,
  ScrollText: <ScrollText />,
  Fingerprint: <Fingerprint />,
  ListFilter: <ListFilter />,
  Bookmark: <Bookmark />,
  Waypoints: <Waypoints />,
  Warehouse: <Warehouse />,
  Flame: <Flame />,
  Wand2: <Wand2 />,
  PenTool: <PenTool />,
  Radar: <Radar />,
  ShieldCheck: <ShieldCheck />,
  UserCheck: <UserCheck />,
  Building2: <Building2 />,
}

export function resolveIcon(icon: string | undefined): ReactElement | undefined {
  if (!icon) return undefined
  return icons[icon]
}
