/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=workers/oauth-protected-resource/wrangler.jsonc --include-runtime=false workers/oauth-protected-resource/worker-configuration.d.ts` (hash: ff08cd04279376914488be5ed1bfdbfc)
interface __BaseEnv_Env {
	RESOURCE_IDENTIFIER: "https://www.librechat.ai";
	AUTHORIZATION_SERVER: "https://librechat.cloudflareaccess.com";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "RESOURCE_IDENTIFIER" | "AUTHORIZATION_SERVER">> {}
}
