export default {
  index: 'Overview',
  mcp: 'MCP',
  agents: 'Agents',
  code_interpreter: 'Code Interpreter API',
  artifacts: 'Artifacts - Generative UI',
  web_search: 'Web Search',
  memory: 'Memory',
  image_gen: 'Image Generation',
  upload_as_text: 'Upload as Text',
  ocr: 'OCR for Documents',
  // local_setup: 'Local Setup',
  // custom_endpoints: 'Custom Endpoints',
  url_query: 'URL Query Parameters',
}
