export default {
  index: 'Intro',
  dotenv: 'Environment Variables',
  librechat_yaml: 'librechat.yaml',
  authentication: 'Authentication',
  mongodb: 'MongoDB',
  redis: 'Redis',
  pre_configured_ai: 'AI Providers',
  tools: 'Tools and Plugins',
  sharepoint: 'SharePoint Files',
  cdn: 'CDN',
  azure: 'Azure OpenAI',
  docker_override: 'Docker Override',
  mod_system: 'Automated Moderation',
}
